version: "3.8"

services:
  backend:
    container_name: malware-scanner-backend
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./incoming:/app/incoming
      - ./scans:/app/scans
    networks:
      - malware_network
    restart: always

  frontend:
    container_name: malware-scanner-frontend
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - malware_network
    restart: always

networks:
  malware_network:
    driver: bridge
